version: "2.2"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "8989:8989"
      - "3789:3789"
    env_file:
      - "web/config/.env"
  web:
    build: ./docker/images/nginx
    container_name: privuma_nginx
    volumes:
      - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template:ro"
      - "/usr/local/hestia/ssl/certificate.crt:/var/ssl.cert:ro"
      - "/usr/local/hestia/ssl/certificate.key:/var/ssl.key:ro"
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - "./web/:/var/www/html/:ro"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-web
    cpu_shares: 256
    mem_limit: 256M
    network_mode: "service:gluetun"
  php-web:
    build:
      context: ./docker/images/php
      args:
        PHP_PORT: 9701
    restart: always
    container_name: privuma_php_web
    env_file:
      - "web/config/.env"
    command: bash -c "echo "" > /etc/cron.d/privuma && php-fpm"
    volumes:
      - ./docker/etc/php/zz-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini:ro
      - ./docker/etc/php/zzz-overrides.conf:/etc/php-fpm.d/zzz-overrides.conf:ro
      - "./web/:/var/www/html/"
    depends_on:
      - db
    cpu_shares: 256
    mem_limit: 1G
    network_mode: "service:gluetun"
  php-cron:
    build:
      context: ./docker/images/php
      args:
        PHP_PORT: 9702
    restart: always
    container_name: privuma_php_cron
    env_file:
      - "web/config/.env"
    volumes:
      - ./docker/etc/php/zz-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini:ro
      - ./docker/etc/php/zzz-overrides.conf:/etc/php-fpm.d/zzz-overrides.conf:ro
      - "./web/:/var/www/html/"
      - "./cron.log:/var/log/cron.log"
    depends_on:
      - db
    cpu_shares: 64
    mem_limit: 2G
    network_mode: "service:gluetun"
  db:
    image: mariadb
    restart: always
    container_name: privuma_db
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=3789
    network_mode: "service:gluetun"
    cpu_shares: 256
    mem_limit: 1G
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/images/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
  cloudfs-http:
    image: rclone/rclone:latest
    container_name: privuma_cloudfs_http
    restart: always
    volumes:
      - ./web/config/rclone:/config/rclone
    user: "${UID}:${GID}"
    network_mode: "service:gluetun"
    command: serve http --read-only --no-checksum --no-modtime --addr :8991 ${CLOUDFS_HTTP_REMOTE} --include *.{jpg,jpeg,png,gif,mp4,mov,webm,pdf,html,txt,js,css,svg,js\-gz,txt\-gz} --dir-cache-time 1m --vfs-cache-mode full --vfs-cache-max-age 30m --vfs-cache-max-size 8G --vfs-read-chunk-size 64M --vfs-read-chunk-size-limit off --buffer-size 64M
  cloudfs-http-secondary:
    image: rclone/rclone:latest
    container_name: privuma_cloudfs_http_secondary
    restart: always
    volumes:
      - ./web/config/rclone:/config/rclone
    user: "${UID}:${GID}"
    network_mode: "service:gluetun"
    command: serve http --read-only --no-checksum --no-modtime --addr :8992 ${CLOUDFS_HTTP_SECONDARY_REMOTE} --include *.{jpg,jpeg,png,gif,mp4,mov,webm,pdf,html,txt,js,css,svg,js\-gz,txt\-gz} --dir-cache-time 1m --vfs-cache-mode full --vfs-cache-max-age 30m --vfs-cache-max-size 8G  --vfs-read-chunk-size 64M --vfs-read-chunk-size-limit off --buffer-size 64M
  cloudfs-http-tertiary:
    image: rclone/rclone:latest
    container_name: privuma_cloudfs_http_teriary
    restart: always
    volumes:
      - ./web/config/rclone:/config/rclone
    user: "${UID}:${GID}"
    network_mode: "service:gluetun"
    command: serve http --read-only --no-checksum --no-modtime --addr :8993 ${CLOUDFS_HTTP_TERTIARY_REMOTE} --include *.{jpg,jpeg,png,gif,mp4,mov,webm,pdf,html,txt,js,css,svg,js\-gz,txt\-gz} --dir-cache-time 1m  --vfs-cache-mode full --vfs-cache-max-age 30m --vfs-cache-max-size 8G --vfs-read-chunk-size 64M --vfs-read-chunk-size-limit off --buffer-size 64M
  # cloudfs-s3:
  #   image: rclone/rclone:beta
  #   container_name: privuma_cloudfs_s3
  #   restart: always
  #   volumes:
  #     - ./web/config/rclone:/config/rclone
  #   user: "${UID}:${GID}"
  #   ports:
  #     - "8994:80"
  #   command: serve s3 --auth-key ${CLOUDFS_S3_ACCESS_KEY},${CLOUDFS_S3_SECRET_KEY} --read-only --no-checksum --no-modtime --addr :80 ${CLOUDFS_S3_REMOTE} --include *.{jpg,jpeg,png,gif,mp4,mov,webm,pdf,html,txt,js,css,svg,js\-gz,txt\-gz} --dir-cache-time 1m --vfs-cache-mode full --vfs-cache-max-age 30m --vfs-cache-max-size 8G --vfs-read-chunk-size 64M --vfs-read-chunk-size-limit off --buffer-size 64M
