version: '3'
services:
    web:
        build: ./docker/images/nginx
        container_name: privuma_nginx
        volumes:
            - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template:ro"
            - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - "./web/:/var/www/html/:ro"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        links:
            - php-web
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php-web
            - mysqldb
    php-web:
        image: cenode/privuma-php
        restart: always
        container_name: privuma_php_web
        env_file:
            - ".env"
        links:
            - mysqldb
            - db
        volumes:
            - ./docker/etc/php/zz-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini:ro
            - ./docker/etc/php/zzz-overrides.conf:/etc/php-fpm.d/zzz-overrides.conf:ro
            - "./web/:/var/www/html/:ro"
        depends_on:
            - mysqldb
            - db
    php-cron:
        image: cenode/privuma-php
        restart: always
        container_name: privuma_php_cron
        env_file:
            - ".env"
        links:
            - mysqldb
            - db
        volumes:
            - ./docker/etc/php/zz-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini:ro
            - ./docker/etc/php/zzz-overrides.conf:/etc/php-fpm.d/zzz-overrides.conf:ro
            - "./web/:/var/www/html/"
        depends_on:
            - mysqldb
            - db
        deploy:
            resources:
                limits:
                    memory: 2G
                reservations:
                    memory: 2G
    # use remote mysql server via an ssh tunnel
    mysqldb:
        restart: always
        container_name: ${MYSQL_HOST}_external
        image: cagataygurturk/docker-ssh-tunnel:0.0.1
        ports:
            - "8990:3306"
        volumes:
            - ./docker/etc/ssh/:/root/ssh:ro
        environment:
            TUNNEL_HOST: mysql-tunnel
            REMOTE_HOST: 127.0.0.1
            LOCAL_PORT: 3306
            REMOTE_PORT: 3306
    puppeteer-renderer:
        restart: always
        container_name: renderer
        ports:
            - '7852:3000'
        image: zenato/puppeteer-renderer
        deploy:
            resources:
                limits:
                    memory: 2G
                reservations:
                    memory: 2G
    db:
        image: mariadb
        restart: always
        container_name: ${MYSQL_HOST}
        environment:
            - MARIADB_DATABASE=${MYSQL_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MARIADB_USER=${MYSQL_USER}
            - MARIADB_PASSWORD=${MYSQL_PASSWORD}
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 1G
        volumes:
            - ./docker/db:/var/lib/mysql
            - ./docker/images/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080